### ISSUE TITLE
Can't apply it on vue 2

### ISSUE THREAD

**Issue by kid-github** [livechat/chat-widget-adapters#27]
**Describe the bug**
I'm using Vue 2 as my framework and the livechat widget guide seems to not working

**To Reproduce**
1. I Use Provided Code from the website to my index ( before </body> tag, as instructed) and it doesnt do anything to my website
![image](https://user-images.githubusercontent.com/53292613/153334464-b7ef9985-31f6-4543-8ab2-93d0df78c36e.png)

2. Then i use this page's direction to Place the code on the app.vue and it's  still not working 
![image](https://user-images.githubusercontent.com/53292613/153334581-87fdeb9f-b654-4110-9095-4771d8f9e16a.png)
![image](https://user-images.githubusercontent.com/53292613/153334609-ff25a063-6d25-4a27-964c-4712f6c9c029.png)

My website still show nothing

Version : Vue 2.6.12

**Comment by walaszczykm** [comment]
Hello @kid-github 👋 

As stated in the `@livechat/widget-vue` package [README](https://github.com/livechat/chat-widget-adapters/blob/master/packages/widget-vue/README.md):

> This library allows to render and interact with the [LiveChat Chat Widget](https://developers.livechat.com/open-chat-widget/) inside a [Vue 3](https://v3.vuejs.org/) application.

It can also be seen from peer dependencies in package.json:
https://github.com/livechat/chat-widget-adapters/blob/832c5cafc34c48950ef1112c9c9b2f335f340558/packages/widget-vue/package.json#L32


This means that we currently support only Vue 3 applications. Vue 3 is currently [the main supported version](https://blog.vuejs.org/posts/vue-3-as-the-new-default.html) of the library. We may enhance support for the `LiveChatWidegt` component to Vue 2 but it will not be a high priority for us at the moment. Hooks exported from the package will not be compatible with Vue 2 as they are based on the [Compistion API](https://v3.vuejs.org/api/composition-api.html) introduced in the Vue 3.

From your screenshot, I can see that in the first place you have used our Chat Widget snippet code directly in your HTML document. This way of integrating Chat Widget with your website is not directly a topic of this project and it should work out of the box for every website. You can read more about it here: https://www.livechat.com/help/setting-up-livechat-on-your-website/.

Could you please provide more details about the issue on your website by embedding the Chat Widget directly in the HTML?

**Comment by walaszczykm** [comment]
Hello, @kid-github once again 👋 

I have looked into this issue and analyzed the reasons for incompatibility. Although the lack of support for the new Composition API is obvious as this is a Vue 3 specific feature, the main `LiveChatWidget` component looked like it could work on both Vue 2 and Vue 3. As long as the component is defined using Options API and not Composition API it will work on both Vue 2 and 3. And indeed it was defined like that but for rich TypeScript support in Vue 3 apps, the component is defined using `defineComponent` function imported from `vue@3` package. This couldn’t work in-app using Vue 2 and missing Vue 3 package. But as usage of this function is not required for runtime in Vue 2 I was able to create a dedicated build pipeline and export this component as plain object export under dedicated submodule `@livechat/widget-vue/v2`. From my tests, it looks that it indeed now works properly on both Vue 2 and Vue 3 apps 🙂 

You can look into a PR for more information and implementation details: https://github.com/livechat/chat-widget-adapters/pull/28

**Comment by walaszczykm** [comment]
The PR was merged. Changes will be available with the next released version 🙂
