### ISSUE TITLE
Params support

### ISSUE THREAD

**Issue by tmyers101** [livechat/chat-widget-adapters#31]
Does this package support a params prop for React? I didn't notice an option for that prop unlike the old react-livechat package.

**Comment by walaszczykm** [comment]
Hello @tmyers101 👋 

The old `params` property was using deprecated name and structure. It is fully available in the new implementation as `sessionVariables` the same way as in our `JS API` method [set_session_variables](https://developers.livechat.com/docs/extending-chat-widget/javascript-api#set-session-variables).

You can read about it in the package description here: [packages/widget-react#config-data](https://github.com/livechat/chat-widget-adapters/tree/master/packages/widget-react#config-data)

The `sessionVariables` accepts a shape of type `Record<string, string>`. Used in the component property can look like this:
```js
<LiveChatWidget
  license="123456"
  sessionVariables={{
    username: "john.doe",
    cart_value: "450"
  }}
/>
```
