### ISSUE TITLE
OpeChatwindow

### ISSUE THREAD

**Issue by mphojkgomo** [livechat/chat-widget-adapters#32]
Seems with the new upgrade the OpenChatWindow has been disregarded and unavailable with the package, this is a good feature that is required when child to main components on Angular. Can you please see this through for us.

**Comment by walaszczykm** [comment]
Hello @mphojkgomo 👋 

If I understand correctly your use case, you would like to open the Chat Widget programmatically from your application.
In such a case, you can simply provide appropriate `visibility` property for `LiveChatWidget` component with  `maximized` as value. The component will reactively respond to the property value change and make Chat Widget maximized.

You can read more about component properties in the package documentation here: [packages/widget-angular#config-data](https://github.com/livechat/chat-widget-adapters/tree/master/packages/widget-angular#config-data)
