### ISSUE TITLE
Add hideMinimizedIcon option into createWidget API

### ISSUE THREAD

**Issue by frankhsiao-ntg** [livechat/chat-widget-adapters#37]
**Is your feature request related to a problem? Please describe.**
We don't want the user to be able to minimize the widget.

**Describe the solution you'd like**
As a developer, createWidget function configs has hideMinimizedIcon option.

**Describe alternatives you've considered**
No.
**Additional context**

**Comment by walaszczykm** [comment]
Hello 👋 

The Chat Widget Adapters project does not exceed the capabilities of the LiveChat Chat Widget used regularly via snipper code. This project aims to provide a convenient integration layer with the LiveChat Chat Widget suited for most popular frameworks like React, Vue, and Angular but it does not introduce any new concepts or features on top of the Chat Widget it is based on.
