### ISSUE TITLE
Usage with Next.js gives failed to load resource

### ISSUE THREAD

**Issue by convert-zia** [livechat/chat-widget-adapters#42]
**Bug Description**
Trying to implement @livechat/widget-react with Next.js but it gives https://cdn.livechatinc.com/tracking.js net::ERR_BLOCKED_BY_CLIENT and is not working

**To Reproduce**
Implementing the code for Livechat as follows:
<LiveChatWidget
      license="MY_LICENSE_KEY"
      group="0"
      visibility={'maximized'}
/>

**Expected behaviour**
The Livechat widget should be shown on the page maximized

**Screenshots**
<img width="1440" alt="Screenshot 2022-05-31 at 9 51 15 PM" src="https://user-images.githubusercontent.com/80040421/171230175-b0479d72-6038-4d4b-9406-8e825689b5f5.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina v10.15.7
 - Browser: Chrome Version 101.0.4951.64 (Official Build) (x86_64)

**Additional context**
    "react": "^17.0.2"
    "next": "12.0.1"
    "@livechat/widget-react": "^1.1.0"

**Comment by walaszczykm** [comment]
Hello @convert-zia 👋 
Thanks for the report. Sad to hear you have encountered an issue with the library.

The error you have encountered while trying to load our `https://cdn.livechatinc.com/tracking.js` is most probably related to the AdBlock-like browser extension. Error message directly points to the reason for request failure: the client (your web browser) has blocked an outgoing request to load our code from the CDN.

Please try again without any of such extensions enabled and let us know if the error is still present.
