### ISSUE TITLE
Target react 18

### ISSUE THREAD

**Issue by bladl** [livechat/chat-widget-adapters#46]
There is react 18 out, please update your package.json

**Comment by vladzagorski** [comment]
Any ETA for the next release?

**Comment by walaszczykm** [comment]
Hello everyone 👋  the PR is open #49 🙂

**Comment by walaszczykm** [comment]
And new version supporting React 18 is published [@livechat/widget-react@1.2.0](https://www.npmjs.com/package/@livechat/widget-react/v/1.2.0) 🙂
