### ISSUE TITLE
Request can set customer messages

### ISSUE THREAD

**Issue by dickyindra** [livechat/chat-widget-adapters#52]
**Is your feature request related to a problem? Please describe.**
I want when the user presses the live chat button, the message in the live chat widget is automatically filled with the message the developer wants.

**Describe the solution you'd like**
Added setter methods to set customer messages such as set customer name or email currently available.

**Describe alternatives you've considered**
Currently there is no other alternative

**Comment by walaszczykm** [comment]
Hello @dickyindra 👋 

Thanks for reaching out to us with your feature request. Unfortunately, the changes you have described are not part of this project. To use such functionality, it would need to be first implemented in the LiveChat Widget application for Adapters to be able to use it. 

We will discuss your request in the team and let you know if it is something that we will add to the main application 🙂

**Comment by dickyindra** [comment]
Ok i'm waiting for the good news, thank you 🙂
