### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by bladl** [livechat/chat-widget-adapters#54]
There is an error in console related to [live chat tracking file](https://cdn.livechatinc.com/tracking.js).
Error happens immediately after widget load. 

<img width="503" alt="Screenshot 2022-08-19 at 15 08 19" src="https://user-images.githubusercontent.com/32598874/185615955-5046ad3a-5097-4e33-9353-73970998d395.png">

 - OS: MacOS
 - Browser Safari
 - Version 15.6.1

**Comment by walaszczykm** [comment]
Hello @bladl 👋
Thanks for the report. Sad to hear you have encountered an issue.

We have tested all three Chat Widget adapters (React, Vue and Angular) on the newest Safari version 15.6.1 and we couldn't reproduce your described issue. 

Could please send us more details?
- used the adapter package and version
- your LiveChat Chat Widget setup, how it is embedded, are you using any particular features?
- how do you load the widget, is it always available or only loaded on a specific page?
- steps to reproduce, maybe you are doing some specific steps with Chat Widget before the issue occurs

**Comment by bladl** [comment]
Sure!
I have noticed that error happens only in Safari. With Chrome everything works as expected.
I use React widget in NextJs app.
Widget is always available.
No specific steps done with Chat Widget.

Here is a stack trace

<img width="577" alt="Screenshot 2022-08-26 at 14 54 30" src="https://user-images.githubusercontent.com/32598874/186899507-0c979fa9-7522-4b05-9907-05b3755935cf.png">
