### ISSUE TITLE
Set LiveChat Customer Avatar

### ISSUE THREAD

**Issue by davidkircos** [livechat/chat-widget-adapters#59]
You can set `customerName` and `customerEmail`. It seems like it should be possible also to set the avatar.

<img width="508" alt="Screen Shot 2022-12-06 at 11 31 20 AM" src="https://user-images.githubusercontent.com/3479421/205992920-9efb2070-f2cb-4cda-9953-1f07e35c4bba.png">

**Comment by walaszczykm** [comment]
Hello, @davidkircos 👋 thanks for your question.
The Chat Widget Adapters projects provide a wrapper layer between LiveChat Chat widget application and one of the supported fronted frameworks of choice.

**What does it do?** It makes it easier to embed LiveChat Chat Widget and interact with it. 
**What does it not do?** It is not extending nor altering already existing LiveChat Chat Widget functionalities.

Setting customer `email` and `name` is currently supported by LiveChat Chat widget JS API while setting customer avatars is currently not as seen on the official documentation: https://developers.livechat.com/docs/extending-chat-widget/javascript-api#setters.

Either way, thanks for the feature request to the Chat Widget application itself 🙂
