### ISSUE TITLE
Angular v15 update

### ISSUE THREAD

**Issue by ectuser** [livechat/chat-widget-adapters#61]
**Is your feature request related to a problem? Please describe.**
I am using Angular livechat widget package in the Angular app. I would like to have the latest version supported.

**Describe the solution you'd like**
PR - https://github.com/livechat/chat-widget-adapters/pull/60

**Comment by ectuser** [comment]
Hi @walaszczykm, could you please take a look? Since there's a Pull request created and I have not spotted any issues, it should not take a long time.

Thank you!

**Comment by walaszczykm** [comment]
The issue has been resolved in #60 and released to npm in version [1.2.2](https://www.npmjs.com/package/@livechat/widget-angular/v/1.2.2)

**Comment by ectuser** [comment]
Hello @walaszczykm! Thank you so much for merging those changes. However I actually only updated to the v14 😄 . Should I create another PR with update to v15?

**Comment by ectuser** [comment]
Created a new PR - https://github.com/livechat/chat-widget-adapters/pull/64

Created a new issue - https://github.com/livechat/chat-widget-adapters/issues/61
