### ISSUE TITLE
Angular v15 update 

### ISSUE THREAD

**Issue by ectuser** [livechat/chat-widget-adapters#65]
**Is your feature request related to a problem? Please describe.**
Update to Angular v15

**Describe the solution you'd like**
https://github.com/livechat/chat-widget-adapters/pull/64

**Additional context**
Previous issue (https://github.com/livechat/chat-widget-adapters/issues/61) was not fully covered v15 migration. So, I've created a new PR with update to v15

**Comment by walaszczykm** [comment]
From my tests, the current version can be easily installed in the Angular 15 project and works fine without upgrading the Angular version used for building the package. To properly support older versions of Angular, we have yet to upgrade the used version for the package built.

**Comment by walaszczykm** [comment]
Here is a mentioned PR: https://github.com/livechat/chat-widget-adapters/pull/67
