### ISSUE TITLE
Add SvelteKit Support

### ISSUE THREAD

**Issue by ghost** [livechat/chat-widget-adapters#66]
**Is your feature request related to a problem? Please describe.**
I am trying to develop a website for a client that uses Livechat. They want to implement your software into their website, but Since I useSveltekit there is a problem with doing that,

**Describe the solution you'd like**
I would like the vue support to be adapted to work for sveltekit as well. This should be simple as svelte and vue are very similar. Some people have written scripts to do that exact thing.

**Describe alternatives you've considered**
Non that I can think of

**Comment by BlockSpeed03** [comment]
The account that was deleted was mine. I am changing the account sorry about that.
