### ISSUE TITLE
Intermittent white bar on bottom on mobile devices

### ISSUE THREAD

**Issue by jeremypokeefe** [livechat/chat-widget-adapters#68]
**Describe the bug**
On some mobile devices we are experiencing a white bar behind the chat widget that is restricting viewing the bottom of the screen. It is not happening on all devices, but we've verified it happens on:

- Pixel 6 Android 13 with Chrome browser version 108
- iPhone 14 with Safari
- iPhone 12 Mini with Safari

**To Reproduce**
1. Install the @livechat/widget-react package
2. Add the plugin to the App.tsx page.
Here's an example of how/where we add the widget
`function App() {
  return (
    <AppProvider>
      <CacheProvider value={clientSideEmotionCache}>
        <ThemeProvider theme={themes()}>
          <CssBaseline />
          <SnackbarProvider maxSnack={3}>
            <AuthProvider>
              <DialogProvider>
                <RightDrawerProvider>
                  <Routes />
                </RightDrawerProvider>
              </DialogProvider>
            </AuthProvider>
          </SnackbarProvider>
        </ThemeProvider>
      </CacheProvider>
      <LiveChatWidget license="XXXXXXX" />
    </AppProvider>
  );
}`
4. Start App
5. Notice the white bar across the bottom of the screen

**Expected behavior**
We expected the widget to float above the components instead of taking up the entire row.

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6693398/212158892-f48ebe9d-478c-49e8-912d-6a1321bfdded.png)

**Desktop (please complete the following information):**
No issues here :)

**Smartphone (please complete the following information):**
- Pixel 6 Android 13 with Chrome browser version 108
- iPhone 14 with Safari
- iPhone 12 Mini with Safari

Please let me know if you need any additional information and I'll be happy to provide it.

Cheers,
Jeremy

**Comment by dgebara00** [comment]
Hello @jeremypokeefe. We are so sorry for the late response. Is the issue still present? Could you specify which iOS version iPhone 14 and 12 used?
