### ISSUE TITLE
Support Angular 16

### ISSUE THREAD

**Issue by timjackleus** [livechat/chat-widget-adapters#76]
**Is your feature request related to a problem? Please describe.**
This angular widget supports up to Angular v15, v16 has now been released.

**Describe the solution you'd like**
It does not seem to be that many breaking changes but rather new features such as signals that are optional. It might be enough to just bump the peer dependancies?

**Describe alternatives you've considered**
To give up on the Angular specific widget and create our own implementation, but I really want to avoid this.

**Comment by walaszczykm** [comment]
Hello 👋 the Issue has been closed by this PR https://github.com/livechat/chat-widget-adapters/pull/78 and the update is available in the newest version on npm https://www.npmjs.com/package/@livechat/widget-angular/v/1.3.1
