### ISSUE TITLE
visibility="minimized" do hide chat icon in mobile view.

### ISSUE THREAD

**Issue by betfocvinod** [livechat/chat-widget-adapters#81]
**Describe the bug**
We are using reactjs live chat packager
Here is the URL : https://www.npmjs.com/package/@livechat/widget-react
<LiveChatWidget license="15633603" visibility="maximized" />
visibility  'maximized' | 'minimized' | 'hidden'

visibility="minimized" do hide chat icon in mobile view, due to this all mobile user not able to see chat icon with this visibility.

**To Reproduce**
1. Go to the website where live chat widget added using reactjs.
2. In mobile android device it is not showing chat icon, iPhone I did not check, you need to check it.

**Expected behavior**
I am assuming that chat icon should visible in minimized mode, it should not open but show chat icon.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mobile OS
 - Browser [chrome, safari] you can check in the all browser.
 - Version [All version]

**Smartphone (please complete the following information):**
 - Device: [All devices]
 - OS: [All OS]
 - Browser [chrome, safari]
 - Version [all]

**Additional context**

**Comment by dgebara00** [comment]
Hello @betfocvinod. I was inspecting your case, but unfortunately, I couldn't reproduce the issue with the widget. It looks like you may have changed the visibility settings particularly for mobile. There's the screenshot where you can find how to change that.

![Screenshot 2023-09-29 at 01 24 08](https://github.com/livechat/chat-widget-adapters/assets/74222613/78d07ea1-12e7-475a-ae18-031c8d41e9ed)

If changing the settings doesn't fix the issue, please let us know, and we will continue to find the solution.
