### ISSUE TITLE
Update library to support Angular v18 compatibility

### ISSUE THREAD

**Issue by tonisiforou** [livechat/chat-widget-adapters#94]
Dependency conflicts: Please update the library to enable migration to Angular v18.

**Comment by tonisiforou** [comment]
Hello! Could you please provide an update on the progress of this?
@walaszczykm

**Comment by md-idea** [comment]
Hi. Is this there an update on this one?

**Comment by walaszczykm** [comment]
Hello, thanks for reporting the issue, and sorry for the delay. 

I will take a look at this one this week. There is already an open PR to address it but it only updates peer dependencies while not making and upgrade for test purposes https://github.com/livechat/chat-widget-adapters/pull/95

**Comment by thelitlej** [comment]
> Hello, thanks for reporting the issue, and sorry for the delay.
> 
> I will take a look at this one this week. There is already an open PR to address it but it only updates peer dependencies while not making and upgrade for test purposes #95

What is happening with this, what was the result looking in to it two weeks ago?

**Comment by walaszczykm** [comment]
The new version supporting Angular 18 was released as `v1.3.3`
https://www.npmjs.com/package/@livechat/widget-angular/v/1.3.3
